modLoader = "javafml"
loaderVersion = "[1,)"
license = "ARR"
issueTrackerURL = "https://github.com/terrarium-earth/Tempad/issues"

[[mods]]
modId = "tempad"
version = "${version}"
displayName = "Tempad"
displayURL = "https://modrinth.com/mod/tempad"
logoFile = "icon.png"
authors = "CodexAdrian"
credits = "ShrimpPixels, Facu, MsRandom1, ThatGravyBoat, Kekie6"
description = "Create a portal to anywhere from anywhere!"
enumExtensions="META-INF/enum_extensions.json"
featureFlags="META-INF/feature_flags.json"

[[mixins]]
config = "META-INF/tempad.mixins.json"

[[dependencies.tempad]]
modId = "neoforge"
type = "required"
versionRange = "[20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tempad]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tempad]]
modId = "resourcefullib"
type = "required"
versionRange = "[3.0.12,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tempad]]
modId = "resourcefulconfig"
type = "required"
versionRange = "[3.0.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tempad]]
modId = "kotlinforforge"
type = "required"
versionRange = "[5.3.0,)"
ordering = "NONE"
side = "BOTH"
